version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: boilerplate_next
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgress_pass
      POSTGRES_DB: db_next
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
